# Generated by Django 5.0.7 on 2025-07-23 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cuidador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("sobrenome", models.CharField(max_length=100)),
                ("data_nascimento", models.DateField(blank=True, null=True)),
                ("cpf", models.CharField(max_length=14, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("senha", models.CharField(default="123456", max_length=128)),
                (
                    "foto_perfil",
                    models.ImageField(blank=True, null=True, upload_to="perfil/"),
                ),
                ("telefone", models.CharField(max_length=15)),
                ("cep", models.CharField(max_length=8, null=True)),
                ("estado", models.CharField(max_length=100, null=True)),
                ("cidade", models.CharField(max_length=100, null=True)),
                ("rua", models.CharField(max_length=100)),
                ("numero", models.CharField(default="S/N", max_length=10)),
                ("instagram", models.CharField(blank=True, max_length=100, null=True)),
                ("disponivel", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Tutor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("sobrenome", models.CharField(max_length=100)),
                ("data_nascimento", models.DateField(blank=True, null=True)),
                ("cpf", models.CharField(max_length=14, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("senha", models.CharField(default="123456", max_length=128)),
                (
                    "foto_perfil",
                    models.ImageField(blank=True, null=True, upload_to="perfil/"),
                ),
                (
                    "plataforma_indicacao",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CaracteristicasCuidador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("estudante_de_veterinaria", models.BooleanField(default=False)),
                ("medico_veterinario", models.BooleanField(default=False)),
                ("capacidade_adestramento", models.BooleanField(default=False)),
                ("aceita_multiplos_pets", models.BooleanField(default=False)),
                ("pet_ate_5kg", models.BooleanField(default=False)),
                ("pet_5kg_a_10kg", models.BooleanField(default=False)),
                ("pet_10kg_a_20kg", models.BooleanField(default=False)),
                ("pet_20kg_a_40kg", models.BooleanField(default=False)),
                ("so_pet_castrado", models.BooleanField(default=False)),
                ("pet_nao_castrado", models.BooleanField(default=False)),
                ("pet_femea", models.BooleanField(default=False)),
                ("pet_macho", models.BooleanField(default=False)),
                ("medicacao_oral", models.BooleanField(default=False)),
                ("medicacao_injetavel", models.BooleanField(default=False)),
                (
                    "cuidador",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="caracteristicas",
                        to="nanny_pets_app.cuidador",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AvaliacaoCuidador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nota", models.PositiveSmallIntegerField()),
                ("comentario", models.TextField(blank=True)),
                ("data_hora", models.DateTimeField(auto_now_add=True)),
                (
                    "cuidador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avaliacoes",
                        to="nanny_pets_app.cuidador",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImagemAmbiente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("foto", models.ImageField(upload_to="ambientes/")),
                (
                    "cuidador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imagens",
                        to="nanny_pets_app.cuidador",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("especie", models.CharField(max_length=50)),
                ("raca", models.CharField(blank=True, max_length=50, null=True)),
                ("porte", models.CharField(max_length=20)),
                ("idade", models.PositiveIntegerField()),
                ("castrado", models.BooleanField(default=False)),
                (
                    "genero",
                    models.CharField(
                        choices=[("Macho", "Macho"), ("Fêmea", "Fêmea")], max_length=10
                    ),
                ),
                ("foto", models.ImageField(blank=True, null=True, upload_to="pets/")),
                ("observacoes", models.TextField(blank=True, null=True)),
                (
                    "tutor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pets",
                        to="nanny_pets_app.tutor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField()),
                ("observacoes", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("aprovado", "Aprovado"),
                            ("recusado", "Recusado"),
                            ("concluido", "Concluído"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="pendente",
                        max_length=10,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "cuidador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pedidos_recebidos",
                        to="nanny_pets_app.cuidador",
                    ),
                ),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nanny_pets_app.pet",
                    ),
                ),
                (
                    "tutor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pedidos",
                        to="nanny_pets_app.tutor",
                    ),
                ),
            ],
        ),
    ]
