# Generated by Django 5.0.7 on 2025-07-23 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nanny_pets_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="caracteristicascuidador",
            name="aceita_multiplos_pets",
        ),
        migrations.RemoveField(
            model_name="caracteristicascuidador",
            name="capacidade_adestramento",
        ),
        migrations.RemoveField(
            model_name="caracteristicascuidador",
            name="cuidador",
        ),
        migrations.RemoveField(
            model_name="caracteristicascuidador",
            name="estudante_de_veterinaria",
        ),
        migrations.RemoveField(
            model_name="caracteristicascuidador",
            name="medicacao_injetavel",
        ),
        migrations.RemoveField(
            model_name="caracteristicascuidador",
            name="medicacao_oral",
        ),
        migrations.RemoveField(
            model_name="caracteristicascuidador",
            name="medico_veterinario",
        ),
        migrations.RemoveField(
            model_name="caracteristicascuidador",
            name="pet_10kg_a_20kg",
        ),
        migrations.RemoveField(
            model_name="caracteristicascuidador",
            name="pet_20kg_a_40kg",
        ),
        migrations.RemoveField(
            model_name="caracteristicascuidador",
            name="pet_5kg_a_10kg",
        ),
        migrations.RemoveField(
            model_name="caracteristicascuidador",
            name="pet_ate_5kg",
        ),
        migrations.RemoveField(
            model_name="caracteristicascuidador",
            name="pet_femea",
        ),
        migrations.RemoveField(
            model_name="caracteristicascuidador",
            name="pet_macho",
        ),
        migrations.RemoveField(
            model_name="caracteristicascuidador",
            name="pet_nao_castrado",
        ),
        migrations.RemoveField(
            model_name="caracteristicascuidador",
            name="so_pet_castrado",
        ),
        migrations.AddField(
            model_name="caracteristicascuidador",
            name="nome",
            field=models.CharField(default="123456", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cuidador",
            name="caracteristicas",
            field=models.ManyToManyField(
                blank=True,
                related_name="cuidadores",
                to="nanny_pets_app.caracteristicascuidador",
            ),
        ),
    ]
