# Generated by Django 5.0.7 on 2025-07-23 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "nanny_pets_app",
            "0002_remove_caracteristicascuidador_aceita_multiplos_pets_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedido",
            name="status",
            field=models.CharField(
                choices=[
                    ("pendente", "Pendente"),
                    ("aprovado", "Aprovado"),
                    ("recusado", "Recusado"),
                    ("cancelado", "Cancelado"),
                ],
                default="pendente",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="pet",
            name="porte",
            field=models.CharField(
                choices=[
                    ("pequeno", "Pequeno"),
                    ("medio", "Médio"),
                    ("grande", "Grande"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Hospedagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("confirmada", "Confirmada"),
                            ("em_andamento", "Em andamento"),
                            ("finalizada", "Finalizada"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="confirmada",
                        max_length=20,
                    ),
                ),
                ("observacoes", models.TextField(blank=True)),
                (
                    "cuidador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hospedagens",
                        to="nanny_pets_app.cuidador",
                    ),
                ),
                (
                    "pedido",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="nanny_pets_app.pedido",
                    ),
                ),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hospedagens",
                        to="nanny_pets_app.pet",
                    ),
                ),
                (
                    "tutor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hospedagens",
                        to="nanny_pets_app.tutor",
                    ),
                ),
            ],
        ),
    ]
