# Generated by Django 5.0.7 on 2025-07-23 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nanny_pets_app", "0003_alter_pedido_status_alter_pet_porte_hospedagem"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="tutor",
            name="user",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tutor",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
