# Generated by Django 5.0.7 on 2025-07-23 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nanny_pets_app", "0005_cuidador_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="avaliacaocuidador",
            name="hospedagem",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="avaliacao",
                to="nanny_pets_app.hospedagem",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="avaliacaocuidador",
            name="tutor",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="avaliacoes",
                to="nanny_pets_app.tutor",
            ),
            preserve_default=False,
        ),
    ]
