# Generated by Django 5.0.7 on 2025-07-23 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nanny_pets_app", "0006_avaliacaocuidador_hospedagem_avaliacaocuidador_tutor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cuidador",
            name="foto_perfil",
            field=models.ImageField(
                blank=True, default="defaults/avatar_padrao.png", upload_to="uploads/"
            ),
        ),
        migrations.AlterField(
            model_name="tutor",
            name="foto_perfil",
            field=models.ImageField(
                blank=True, default="defaults/avatar_padrao.png", upload_to="uploads/"
            ),
        ),
    ]
