# Generated by Django 4.2.3 on 2023-10-11 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanny_pets_app', '0002_avaliacuidador_caracteristicas_imagens'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoCuidador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField()),
                ('comentario', models.TextField()),
                ('data_hora', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='AvaliaCuidador',
        ),
    ]
