# Generated by Django 4.2.3 on 2023-10-25 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nanny_pets_app', '0003_avaliacaocuidador_delete_avaliacuidador'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaliacaocuidador',
            options={'verbose_name_plural': 'Avaliações do Cuidador'},
        ),
        migrations.AlterModelOptions(
            name='avaliacaotutor',
            options={'verbose_name_plural': 'Avaliações do Tutor'},
        ),
        migrations.AlterModelOptions(
            name='caracteristicas',
            options={'verbose_name_plural': 'Características'},
        ),
        migrations.AlterModelOptions(
            name='cuidador',
            options={'verbose_name_plural': 'Cuidadores'},
        ),
        migrations.AlterModelOptions(
            name='imagens',
            options={'verbose_name_plural': 'Imagens'},
        ),
        migrations.AlterModelOptions(
            name='tutor',
            options={'verbose_name_plural': 'Tutores'},
        ),
        migrations.AddField(
            model_name='caracteristicas',
            name='cuidador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='caracteristicas', to='nanny_pets_app.cuidador'),
            preserve_default=False,
        ),
    ]
