# Generated by Django 4.2.3 on 2023-10-25 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nanny_pets_app', '0004_alter_avaliacaocuidador_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagens',
            name='cuidador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='nanny_pets_app.cuidador'),
            preserve_default=False,
        ),
    ]
