# Generated by Django 4.2.3 on 2023-10-25 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nanny_pets_app', '0005_imagens_cuidador'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacaocuidador',
            name='cuidador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='avaliacaocuidador', to='nanny_pets_app.cuidador'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avaliacaotutor',
            name='tutor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tutor', to='nanny_pets_app.cuidador'),
            preserve_default=False,
        ),
    ]
