# Generated by Django 4.2.3 on 2023-10-25 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nanny_pets_app', '0006_avaliacaocuidador_cuidador_avaliacaotutor_tutor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagensAmbiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotos_local', models.ImageField(upload_to='')),
                ('cuidador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagensambiente', to='nanny_pets_app.cuidador')),
            ],
            options={
                'verbose_name_plural': 'Imagens',
            },
        ),
        migrations.DeleteModel(
            name='Imagens',
        ),
    ]
