# Generated by Django 4.2.3 on 2023-10-25 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nanny_pets_app', '0007_imagensambiente_delete_imagens'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaliacaocuidador',
            options={'verbose_name_plural': 'Avaliações do cuidador'},
        ),
        migrations.AlterModelOptions(
            name='avaliacaotutor',
            options={'verbose_name_plural': 'Avaliações do tutor'},
        ),
        migrations.AlterModelOptions(
            name='imagensambiente',
            options={'verbose_name_plural': 'Imagens do ambiente'},
        ),
    ]
