# Generated by Django 4.2.3 on 2023-10-31 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanny_pets_app', '0009_alter_avaliacaotutor_tutor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='teste',
        ),
        migrations.AddField(
            model_name='tutor',
            name='plataformaIndicação',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
