# Generated by Django 4.2.3 on 2023-10-31 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nanny_pets_app', '0010_remove_tutor_teste_tutor_plataformaindicação'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caracteristicas',
            name='cuidador',
        ),
        migrations.AddField(
            model_name='cuidador',
            name='caracteristicas',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nanny_pets_app.caracteristicas'),
        ),
    ]
