# Generated by Django 4.2.3 on 2023-10-31 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nanny_pets_app', '0011_remove_caracteristicas_cuidador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuidador',
            name='caracteristicas',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='nanny_pets_app.caracteristicas'),
        ),
    ]
