# Generated by Django 4.2.3 on 2023-10-31 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nanny_pets_app', '0012_alter_cuidador_caracteristicas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuidador',
            name='caracteristicas',
        ),
        migrations.AddField(
            model_name='caracteristicas',
            name='cuidador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='caracteristicas', to='nanny_pets_app.cuidador'),
            preserve_default=False,
        ),
    ]
