# Generated by Django 5.0 on 2023-12-22 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanny_pets_app', '0014_alter_cuidador_data_nascimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuidador',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
