# Generated by Django 5.0 on 2023-12-28 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanny_pets_app', '0015_alter_cuidador_foto_perfil_alter_tutor_foto_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuidador',
            name='endereco',
        ),
        migrations.AddField(
            model_name='cuidador',
            name='cep',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='cuidador',
            name='cidade',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cuidador',
            name='estado',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cuidador',
            name='numero',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cuidador',
            name='rua',
            field=models.IntegerField(default=0),
        ),
    ]
