# Generated by Django 5.0 on 2023-12-29 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanny_pets_app', '0016_remove_cuidador_endereco_cuidador_cep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuidador',
            name='rua',
            field=models.CharField(max_length=100),
        ),
    ]
