# Generated by Django 5.0.7 on 2024-08-27 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nanny_pets_app", "0017_alter_cuidador_rua"),
    ]

    operations = [
        migrations.AddField(
            model_name="cuidador",
            name="senha",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="tutor",
            name="senha",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
